- name: Install Packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - apache2 
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

